root = "."
tmp_dir = "tmp"

[watch]
dirs = ["cmd", "internal"]
exclude_dirs = ["web/client/mnotes/node_modules", "web/client/mnotes/build", "tmp"]


[build]
cmd = "cmd/mnotes-backend"
bin = "tmp/main.exe"
full_bin = "tmp/main.exe"
